
/*
Auto-generated by CVXPYgen on November 29, 2023 at 21:15:35.
Content: Function declarations.
*/

#include "cpg_workspace.h"

// Update user-defined parameter values
extern void cpg_update_X_ref(c_int idx, c_float val);
extern void cpg_update_x_init(c_int idx, c_float val);
extern void cpg_update_A_dyn(c_int idx, c_float val);
extern void cpg_update_Inertial_matrix(c_int idx, c_float val);

// Map user-defined to canonical parameters
extern void cpg_canonicalize_A();
extern void cpg_canonicalize_b();
extern void cpg_canonicalize_G();
extern void cpg_canonicalize_h();

// Retrieve primal solution in terms of user-defined variables
extern void cpg_retrieve_prim();

// Retrieve dual solution in terms of user-defined constraints
extern void cpg_retrieve_dual();

// Retrieve solver information
extern void cpg_retrieve_info();

// Solve via canonicalization, canonical solve, retrieval
extern void cpg_solve();

// Update solver settings
extern void cpg_set_solver_default_settings();
extern void cpg_set_solver_feastol(c_float feastol_new);
extern void cpg_set_solver_abstol(c_float abstol_new);
extern void cpg_set_solver_reltol(c_float reltol_new);
extern void cpg_set_solver_feastol_inacc(c_float feastol_inacc_new);
extern void cpg_set_solver_abstol_inacc(c_float abstol_inacc_new);
extern void cpg_set_solver_reltol_inacc(c_float reltol_inacc_new);
extern void cpg_set_solver_maxit(c_int maxit_new);
