
/*
Auto-generated by CVXPYgen on November 29, 2023 at 21:15:35.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static c_int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_X_ref(0, 0.00000000000000000000);
  cpg_update_x_init(0, 0.00000000000000000000);
  cpg_update_A_dyn(0, 0.00000000000000000000);
  cpg_update_Inertial_matrix(0, 0.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<96; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<42; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }
  for(i=0; i<16; i++) {
    printf("X_cmp[%d] = %f\n", i, CPG_Result.prim->X_cmp[i]);
  }

  // Print dual solution
  for(i=0; i<12; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<12; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", CPG_Result.dual->d2);
  printf("d3 = %f\n", CPG_Result.dual->d3);
  printf("d4 = %f\n", CPG_Result.dual->d4);
  printf("d5 = %f\n", CPG_Result.dual->d5);
  printf("d6 = %f\n", CPG_Result.dual->d6);
  printf("d7 = %f\n", CPG_Result.dual->d7);
  printf("d8 = %f\n", CPG_Result.dual->d8);
  printf("d9 = %f\n", CPG_Result.dual->d9);
  printf("d10 = %f\n", CPG_Result.dual->d10);
  printf("d11 = %f\n", CPG_Result.dual->d11);
  printf("d12 = %f\n", CPG_Result.dual->d12);
  for(i=0; i<12; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  printf("d14 = %f\n", CPG_Result.dual->d14);
  printf("d15 = %f\n", CPG_Result.dual->d15);
  printf("d16 = %f\n", CPG_Result.dual->d16);
  printf("d17 = %f\n", CPG_Result.dual->d17);
  printf("d18 = %f\n", CPG_Result.dual->d18);
  printf("d19 = %f\n", CPG_Result.dual->d19);
  printf("d20 = %f\n", CPG_Result.dual->d20);
  printf("d21 = %f\n", CPG_Result.dual->d21);
  printf("d22 = %f\n", CPG_Result.dual->d22);
  printf("d23 = %f\n", CPG_Result.dual->d23);
  printf("d24 = %f\n", CPG_Result.dual->d24);
  for(i=0; i<12; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  printf("d26 = %f\n", CPG_Result.dual->d26);
  printf("d27 = %f\n", CPG_Result.dual->d27);
  printf("d28 = %f\n", CPG_Result.dual->d28);
  printf("d29 = %f\n", CPG_Result.dual->d29);
  printf("d30 = %f\n", CPG_Result.dual->d30);
  printf("d31 = %f\n", CPG_Result.dual->d31);
  printf("d32 = %f\n", CPG_Result.dual->d32);
  printf("d33 = %f\n", CPG_Result.dual->d33);
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  for(i=0; i<12; i++) {
    printf("d37[%d] = %f\n", i, CPG_Result.dual->d37[i]);
  }
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  for(i=0; i<12; i++) {
    printf("d49[%d] = %f\n", i, CPG_Result.dual->d49[i]);
  }
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  printf("d54 = %f\n", CPG_Result.dual->d54);
  printf("d55 = %f\n", CPG_Result.dual->d55);
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  for(i=0; i<12; i++) {
    printf("d61[%d] = %f\n", i, CPG_Result.dual->d61[i]);
  }
  printf("d62 = %f\n", CPG_Result.dual->d62);
  printf("d63 = %f\n", CPG_Result.dual->d63);
  printf("d64 = %f\n", CPG_Result.dual->d64);
  printf("d65 = %f\n", CPG_Result.dual->d65);
  printf("d66 = %f\n", CPG_Result.dual->d66);
  printf("d67 = %f\n", CPG_Result.dual->d67);
  printf("d68 = %f\n", CPG_Result.dual->d68);
  printf("d69 = %f\n", CPG_Result.dual->d69);
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  printf("d72 = %f\n", CPG_Result.dual->d72);
  for(i=0; i<12; i++) {
    printf("d73[%d] = %f\n", i, CPG_Result.dual->d73[i]);
  }
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  printf("d76 = %f\n", CPG_Result.dual->d76);
  printf("d77 = %f\n", CPG_Result.dual->d77);
  printf("d78 = %f\n", CPG_Result.dual->d78);
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  printf("d81 = %f\n", CPG_Result.dual->d81);
  printf("d82 = %f\n", CPG_Result.dual->d82);
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);

  return 0;

}
