
/*
Auto-generated by CVXPYgen on December 01, 2023 at 10:05:35.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"
#include "workspace.h"
#include "osqp.h"

static c_int i;
static c_int j;

// Update user-defined parameters
void cpg_update_X_ref(c_int idx, c_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.l = 1;
  Canon_Outdated.u = 1;
}

void cpg_update_L_ref(c_int idx, c_float val){
  cpg_params_vec[idx+84] = val;
  Canon_Outdated.l = 1;
  Canon_Outdated.u = 1;
}

void cpg_update_x_init(c_int idx, c_float val){
  cpg_params_vec[idx+98] = val;
  Canon_Outdated.l = 1;
  Canon_Outdated.u = 1;
}

void cpg_update_A_dyn(c_int idx, c_float val){
  cpg_params_vec[idx+110] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Z_c(c_float val){
  cpg_params_vec[1118] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_J_ini(c_int idx, c_float val){
  cpg_params_vec[idx+1119] = val;
  Canon_Outdated.A = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<1587; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_l(){
  for(i=0; i<257; i++){
    Canon_Params.l[i] = 0;
    for(j=canon_l_map.p[i]; j<canon_l_map.p[i+1]; j++){
      Canon_Params.l[i] += canon_l_map.x[j]*cpg_params_vec[canon_l_map.i[j]];
    }
  }
}

void cpg_canonicalize_u(){
  for(i=0; i<313; i++){
    Canon_Params.u[i] = 0;
    for(j=canon_u_map.p[i]; j<canon_u_map.p[i+1]; j++){
      Canon_Params.u[i] += canon_u_map.x[j]*cpg_params_vec[canon_u_map.i[j]];
    }
  }
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d2 = workspace.solution->y[164];
  CPG_Dual.d3 = workspace.solution->y[165];
  CPG_Dual.d4 = workspace.solution->y[257];
  CPG_Dual.d5 = workspace.solution->y[258];
  CPG_Dual.d6 = workspace.solution->y[259];
  CPG_Dual.d7 = workspace.solution->y[260];
  CPG_Dual.d8 = workspace.solution->y[261];
  CPG_Dual.d9 = workspace.solution->y[262];
  CPG_Dual.d10 = workspace.solution->y[263];
  CPG_Dual.d11 = workspace.solution->y[264];
  CPG_Dual.d12 = workspace.solution->y[166];
  CPG_Dual.d14 = workspace.solution->y[179];
  CPG_Dual.d15 = workspace.solution->y[180];
  CPG_Dual.d16 = workspace.solution->y[265];
  CPG_Dual.d17 = workspace.solution->y[266];
  CPG_Dual.d18 = workspace.solution->y[267];
  CPG_Dual.d19 = workspace.solution->y[268];
  CPG_Dual.d20 = workspace.solution->y[269];
  CPG_Dual.d21 = workspace.solution->y[270];
  CPG_Dual.d22 = workspace.solution->y[271];
  CPG_Dual.d23 = workspace.solution->y[272];
  CPG_Dual.d24 = workspace.solution->y[181];
  CPG_Dual.d26 = workspace.solution->y[194];
  CPG_Dual.d27 = workspace.solution->y[195];
  CPG_Dual.d28 = workspace.solution->y[273];
  CPG_Dual.d29 = workspace.solution->y[274];
  CPG_Dual.d30 = workspace.solution->y[275];
  CPG_Dual.d31 = workspace.solution->y[276];
  CPG_Dual.d32 = workspace.solution->y[277];
  CPG_Dual.d33 = workspace.solution->y[278];
  CPG_Dual.d34 = workspace.solution->y[279];
  CPG_Dual.d35 = workspace.solution->y[280];
  CPG_Dual.d36 = workspace.solution->y[196];
  CPG_Dual.d38 = workspace.solution->y[209];
  CPG_Dual.d39 = workspace.solution->y[210];
  CPG_Dual.d40 = workspace.solution->y[281];
  CPG_Dual.d41 = workspace.solution->y[282];
  CPG_Dual.d42 = workspace.solution->y[283];
  CPG_Dual.d43 = workspace.solution->y[284];
  CPG_Dual.d44 = workspace.solution->y[285];
  CPG_Dual.d45 = workspace.solution->y[286];
  CPG_Dual.d46 = workspace.solution->y[287];
  CPG_Dual.d47 = workspace.solution->y[288];
  CPG_Dual.d48 = workspace.solution->y[211];
  CPG_Dual.d50 = workspace.solution->y[224];
  CPG_Dual.d51 = workspace.solution->y[225];
  CPG_Dual.d52 = workspace.solution->y[289];
  CPG_Dual.d53 = workspace.solution->y[290];
  CPG_Dual.d54 = workspace.solution->y[291];
  CPG_Dual.d55 = workspace.solution->y[292];
  CPG_Dual.d56 = workspace.solution->y[293];
  CPG_Dual.d57 = workspace.solution->y[294];
  CPG_Dual.d58 = workspace.solution->y[295];
  CPG_Dual.d59 = workspace.solution->y[296];
  CPG_Dual.d60 = workspace.solution->y[226];
  CPG_Dual.d62 = workspace.solution->y[239];
  CPG_Dual.d63 = workspace.solution->y[240];
  CPG_Dual.d64 = workspace.solution->y[297];
  CPG_Dual.d65 = workspace.solution->y[298];
  CPG_Dual.d66 = workspace.solution->y[299];
  CPG_Dual.d67 = workspace.solution->y[300];
  CPG_Dual.d68 = workspace.solution->y[301];
  CPG_Dual.d69 = workspace.solution->y[302];
  CPG_Dual.d70 = workspace.solution->y[303];
  CPG_Dual.d71 = workspace.solution->y[304];
  CPG_Dual.d72 = workspace.solution->y[241];
  CPG_Dual.d74 = workspace.solution->y[254];
  CPG_Dual.d75 = workspace.solution->y[255];
  CPG_Dual.d76 = workspace.solution->y[305];
  CPG_Dual.d77 = workspace.solution->y[306];
  CPG_Dual.d78 = workspace.solution->y[307];
  CPG_Dual.d79 = workspace.solution->y[308];
  CPG_Dual.d80 = workspace.solution->y[309];
  CPG_Dual.d81 = workspace.solution->y[310];
  CPG_Dual.d82 = workspace.solution->y[311];
  CPG_Dual.d83 = workspace.solution->y[312];
  CPG_Dual.d84 = workspace.solution->y[256];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = workspace.info->obj_val;
  CPG_Info.iter = workspace.info->iter;
  CPG_Info.status = workspace.info->status;
  CPG_Info.pri_res = workspace.info->pri_res;
  CPG_Info.dua_res = workspace.info->dua_res;
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
    osqp_update_A(&workspace, Canon_Params.A->x, 0, 0);
  }
  if (Canon_Outdated.l && Canon_Outdated.u) {
    cpg_canonicalize_l();
    cpg_canonicalize_u();
    osqp_update_bounds(&workspace, Canon_Params.l, Canon_Params.u);
  } else if (Canon_Outdated.l) {
    cpg_canonicalize_l();
    osqp_update_lower_bound(&workspace, Canon_Params.l);
  } else if (Canon_Outdated.u) {
    cpg_canonicalize_u();
    osqp_update_upper_bound(&workspace, Canon_Params.u);
  }
  // Solve with OSQP
  osqp_solve(&workspace);
  // Retrieve results
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.P = 0;
  Canon_Outdated.q = 0;
  Canon_Outdated.d = 0;
  Canon_Outdated.A = 0;
  Canon_Outdated.l = 0;
  Canon_Outdated.u = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  osqp_set_default_settings(&settings);
}

void cpg_set_solver_rho(c_float rho_new){
  osqp_update_rho(&workspace, rho_new);
}

void cpg_set_solver_max_iter(c_int max_iter_new){
  osqp_update_max_iter(&workspace, max_iter_new);
}

void cpg_set_solver_eps_abs(c_float eps_abs_new){
  osqp_update_eps_abs(&workspace, eps_abs_new);
}

void cpg_set_solver_eps_rel(c_float eps_rel_new){
  osqp_update_eps_rel(&workspace, eps_rel_new);
}

void cpg_set_solver_eps_prim_inf(c_float eps_prim_inf_new){
  osqp_update_eps_prim_inf(&workspace, eps_prim_inf_new);
}

void cpg_set_solver_eps_dual_inf(c_float eps_dual_inf_new){
  osqp_update_eps_dual_inf(&workspace, eps_dual_inf_new);
}

void cpg_set_solver_alpha(c_float alpha_new){
  osqp_update_alpha(&workspace, alpha_new);
}

void cpg_set_solver_scaled_termination(c_int scaled_termination_new){
  osqp_update_scaled_termination(&workspace, scaled_termination_new);
}

void cpg_set_solver_check_termination(c_int check_termination_new){
  osqp_update_check_termination(&workspace, check_termination_new);
}

void cpg_set_solver_warm_start(c_int warm_start_new){
  osqp_update_warm_start(&workspace, warm_start_new);
}
