#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on November 30, 2023 at 11:36:05.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[294];
extern c_float ldata[313];
extern c_float udata[313];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[294];
extern c_float Dinvscaling[294];
extern c_float Escaling[313];
extern c_float Einvscaling[313];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[607];
extern c_int linsys_solver_P[607];
extern c_float linsys_solver_bp[607];
extern c_float linsys_solver_sol[607];
extern c_float linsys_solver_rho_inv_vec[313];
extern c_int linsys_solver_Pdiag_idx[140];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[140];
extern c_int linsys_solver_AtoKKT[1587];
extern c_int linsys_solver_rhotoKKT[313];
extern QDLDL_float linsys_solver_D[607];
extern QDLDL_int linsys_solver_etree[607];
extern QDLDL_int linsys_solver_Lnz[607];
extern QDLDL_int   linsys_solver_iwork[1821];
extern QDLDL_bool  linsys_solver_bwork[607];
extern QDLDL_float linsys_solver_fwork[607];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[294];
extern c_float ysolution[313];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[313];
extern c_float work_rho_inv_vec[313];
extern c_int work_constr_type[313];
extern c_float work_x[294];
extern c_float work_y[313];
extern c_float work_z[313];
extern c_float work_xz_tilde[607];
extern c_float work_x_prev[294];
extern c_float work_z_prev[313];
extern c_float work_Ax[313];
extern c_float work_Px[294];
extern c_float work_Aty[294];
extern c_float work_delta_y[313];
extern c_float work_Atdelta_y[294];
extern c_float work_delta_x[294];
extern c_float work_Pdelta_x[294];
extern c_float work_Adelta_x[313];
extern c_float work_D_temp[294];
extern c_float work_D_temp_A[294];
extern c_float work_E_temp[313];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
