
/*
Auto-generated by CVXPYgen on December 01, 2023 at 10:05:35.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 84> X_ref;
    std::array<double, 14> L_ref;
    std::array<double, 12> x_init;
    std::array<double, 1008> A_dyn;
    double Z_c;
    std::array<double, 9> J_ini;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool X_ref;
    bool L_ref;
    bool x_init;
    bool A_dyn;
    bool Z_c;
    bool J_ini;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 96> X;
    std::array<double, 42> U;
    std::array<double, 16> X_cmp;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 12> d0;
    std::array<double, 12> d1;
    double d2;
    double d3;
    double d4;
    double d5;
    double d6;
    double d7;
    double d8;
    double d9;
    double d10;
    double d11;
    double d12;
    std::array<double, 12> d13;
    double d14;
    double d15;
    double d16;
    double d17;
    double d18;
    double d19;
    double d20;
    double d21;
    double d22;
    double d23;
    double d24;
    std::array<double, 12> d25;
    double d26;
    double d27;
    double d28;
    double d29;
    double d30;
    double d31;
    double d32;
    double d33;
    double d34;
    double d35;
    double d36;
    std::array<double, 12> d37;
    double d38;
    double d39;
    double d40;
    double d41;
    double d42;
    double d43;
    double d44;
    double d45;
    double d46;
    double d47;
    double d48;
    std::array<double, 12> d49;
    double d50;
    double d51;
    double d52;
    double d53;
    double d54;
    double d55;
    double d56;
    double d57;
    double d58;
    double d59;
    double d60;
    std::array<double, 12> d61;
    double d62;
    double d63;
    double d64;
    double d65;
    double d66;
    double d67;
    double d68;
    double d69;
    double d70;
    double d71;
    double d72;
    std::array<double, 12> d73;
    double d74;
    double d75;
    double d76;
    double d77;
    double d78;
    double d79;
    double d80;
    double d81;
    double d82;
    double d83;
    double d84;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
